/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

//import com.sun.jdi.connect.spi.Connection;
//import java.awt.HeadlessException;
import java.sql.DriverManager;
//import com.mysql.jdbc.SocketFactoryWrapper;
import javax.swing.JOptionPane;
import java.sql.Connection;
//import java.sql.SQLException;
import java.sql.Statement;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import java.sql.*;
import static jframe.DBConnection.con;
//import com.mysql.jdbc.Statement;
/**
 *
 * @author Lenovo
 */
public class library_loginpage extends javax.swing.JFrame {
   // int id;
// String name;
 //String pwd;
 //String email;
 //String contact;
 
 

 /**
     * Creates new form signuppage
     */
    public library_loginpage() {
        initComponents();
    }
    public boolean validatelogin(){
    String name=txt_username.getText();
    String pwd=txt_passward.getText();
    if(name.equals("")){
        JOptionPane.showMessageDialog(this,"please enter username");
    return false;
    }
     if(pwd.equals("")){
        JOptionPane.showMessageDialog(this,"please enter passward");
    return false;
    }
     return true;
    }
    /*  PreparedStatement pst=(PreparedStatement) con.prepareStatement("select * from  user = ? and passward = ?");
    pst.setString(1, name);
    pst.setString(2, pwd);*/
    
    public void login(){
     String name=txt_username.getText();
    String pwd=txt_passward.getText();
    
    try{
          Class.forName("com.mysql.cj.jdbc.Driver");
                  Connection con= DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/library_ms","agam","agam");
  Statement st=con.createStatement();
  //String sql="select * from users where name =? and passward = ?";
  String sql="select name,passward from users";
 //PreparedStatement pst=
         //con.prepareStatement("select * from  user where name = ? and passward = ?");
   // pst.setString(1, name);
  //  pst.setString(2, pwd);
   // ResultSet rs;
         ResultSet  rs = st.executeQuery(sql);
         while(rs.next()){
        //rs.next();
   if(rs.getString(1).equals(name)&&rs.getString(2).equals(pwd)){
       JOptionPane.showMessageDialog(this,"login successful");  
       Homepage home=new Homepage();
       home.setVisible(true);
      this. dispose();
   }}
           
         
  JOptionPane.showMessageDialog(this,"Incorrect username or passward");
 // else{
   //  JOptionPane.showMessageDialog(this,"Incorrect username or passward");
   //       }
    }catch(Exception e){
       e.printStackTrace();
    }}
//public void insertSignupDetails() throws ClassNotFoundException{ 
   /*String name=txt_username.getText();
    String pwd=txt_passward.getText();
     String email=txt_email.getText();
    String contact=txt_contact.getText();
   */
  /*  try{
      Class.forName("com.mysql.cj.jdbc.Driver");
          Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","Nitin*1122");
  //Connection con=DBConnection.getConnection();
  Statement st=con.createStatement();
  String sql="insert into users values('"+name+"','"+pwd+"','"+email+"','"+contact+"')";
// PreparedStatement  pst =(PreparedStatement) con.prepareStatement(sql);
          st.execute(sql);
       // pst.setString(1,name);
      //  pst.setString(2, pwd);
      //  pst.setString(3, email);
      //  pst.setString(4, contact);
        
       
       
        
            JOptionPane.showMessageDialog(this,"Record inserted successfully");
            
        
            // JOptionPane.showMessageDialog(this,"Record insertion failure");
    } catch(Exception e){
       // e.printStackTrace();
       JOptionPane.showMessageDialog(this,e.getMessage());
    }
}*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_passward = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("upmanyu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Nitin's app for calculation ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 250, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Nitin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jframe/engineer-doing-hand-calculations-on-a-calculation-sheet-with-a-calculator-GN1GNG.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 730, 550));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("welcome,to your login page");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, 30));

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("login page");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jframe/2021-12-12_18-39-44_031.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 40));

        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 180, 40));

        jLabel10.setText("USER NAME");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 150, 40));

        jLabel11.setText("PASSWARD");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 150, 40));
        jPanel2.add(txt_passward, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 190, 40));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setForeground(new java.awt.Color(51, 51, 0));
        jButton1.setText("login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 470, 180, 40));

        jButton3.setText("x");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 510, 720));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("welcome To");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 110, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(validatelogin()==true) {
    login();
}      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
     // if(checkDuplicateUser()==true){
       //    JOptionPane.showMessageDialog(this,"user already exit");}
    }//GEN-LAST:event_txt_usernameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(library_loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(library_loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(library_loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(library_loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new library_loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt_passward;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    private static class PreparedS {

        public PreparedS() {
        }
    }

    private static class PrepareStatement {

        public PrepareStatement() {
        }

        private void setString(int i, String name) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
