/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframe;

//import com.sun.jdi.connect.spi.Connection;
//import java.awt.HeadlessException;
import java.sql.DriverManager;
//import com.mysql.jdbc.SocketFactoryWrapper;
import javax.swing.JOptionPane;
import java.sql.Connection;
//import java.sql.SQLException;
import java.sql.Statement;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import java.sql.*;
//import com.mysql.jdbc.Statement;
/**
 *
 * @author Lenovo
 */
public class signuppage extends javax.swing.JFrame {
   // int id;
// String name;
 //String pwd;
 //String email;
 //String contact;
 public void insertSignupDetails(){
     int  id=Integer.parseInt(tf1.getText());
   String name=txt_username.getText();
 String   pwd=txt_passward.getText();
     String email=txt_email.getText();
    String contact=txt_contact.getText();
    try{
      Class.forName("com.mysql.cj.jdbc.Driver");
          Connection con= DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/library_ms","agam","agam");
    Statement st=con.createStatement();
  String sql="insert into users values('"+id+"','"+name+"','"+pwd+"','"+email+"','"+contact+"')";
     st.execute(sql);
      JOptionPane.showMessageDialog(this,"Record inserted successfully");
      library_loginpage page=new  library_loginpage();
      page.setVisible(true);
      dispose();
            
        
            // JOptionPane.showMessageDialog(this,"Record insertion failure");
    } catch(Exception e){
       // e.printStackTrace();
       JOptionPane.showMessageDialog(this,e.getMessage());
    }}
 public boolean validateSignup(){
       int  id=Integer.parseInt(tf1.getText());
   String name=txt_username.getText();
 String   pwd=txt_passward.getText();
     String email=txt_email.getText();
    String contact=txt_contact.getText();
    if(name.equals("")){
          JOptionPane.showMessageDialog(this,"please enter user name");
          return false;
    }
     if(pwd.equals("")){
          JOptionPane.showMessageDialog(this,"please enter passward");
          return false;
    }
      if(email.equals("")||email.matches("'.+@.+\\..+$")){
          JOptionPane.showMessageDialog(this,"please enter valid email");
          return false;
    }
       if(contact.equals("")){
          JOptionPane.showMessageDialog(this,"please enter contact");
          return false;
    }
    return true;
}
 public boolean checkDuplicateUser(){
     String name=txt_username.getText();
     boolean isExit=false;
     try{
         Class.forName("com.mysql.cj.jdbc.Driver");
          Connection con= DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/library_ms","agam","agam");
           PreparedStatement pst=(PreparedStatement) con.prepareStatement("select * from user where name = ?");
           pst.setString(1, name);
           ResultSet rs=pst.executeQuery();
           if(rs.next()){
               isExit=true;
           }else{
             isExit=true;  
           }}
           
     catch(Exception e){
         e.printStackTrace();
     }
     return isExit;
 }
 /**
     * Creates new form signuppage
     */
    public signuppage() {
        initComponents();
    }
//public void insertSignupDetails() throws ClassNotFoundException{ 
   /*String name=txt_username.getText();
    String pwd=txt_passward.getText();
     String email=txt_email.getText();
    String contact=txt_contact.getText();
   */
  /*  try{
      Class.forName("com.mysql.cj.jdbc.Driver");
          Connection con= DriverManager.getConnection("jdbc:mysql://localhost:3306/library_ms","root","Nitin*1122");
  //Connection con=DBConnection.getConnection();
  Statement st=con.createStatement();
  String sql="insert into users values('"+name+"','"+pwd+"','"+email+"','"+contact+"')";
// PreparedStatement  pst =(PreparedStatement) con.prepareStatement(sql);
          st.execute(sql);
       // pst.setString(1,name);
      //  pst.setString(2, pwd);
      //  pst.setString(3, email);
      //  pst.setString(4, contact);
        
       
       
        
            JOptionPane.showMessageDialog(this,"Record inserted successfully");
            
        
            // JOptionPane.showMessageDialog(this,"Record insertion failure");
    } catch(Exception e){
       // e.printStackTrace();
       JOptionPane.showMessageDialog(this,e.getMessage());
    }
}*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_passward = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_contact = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("upmanyu");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 100, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 255));
        jLabel2.setText("Nitin's app for calculation and voting");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 340, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("Nitin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jframe/calculating-graphs-760.jpg"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 730, 550));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CREATE NEW ACCOUNT HERE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 180, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SIGNUP PAGE");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, 30));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jframe/2021-12-12_18-39-44_031.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 40));

        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 180, 40));

        jLabel10.setText("USER NAME");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 150, 40));

        jLabel11.setText("PASSWARD");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, 150, 40));

        jLabel12.setText("Email");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 150, 40));

        jLabel13.setText("contact");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 470, 150, 40));
        jPanel2.add(txt_passward, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 190, 40));

        txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_emailActionPerformed(evt);
            }
        });
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 190, 40));
        jPanel2.add(txt_contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, 190, 40));

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setForeground(new java.awt.Color(51, 51, 0));
        jButton1.setText("login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 610, 180, 40));

        jButton2.setBackground(new java.awt.Color(255, 51, 51));
        jButton2.setForeground(new java.awt.Color(51, 51, 0));
        jButton2.setText("signup");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 180, 40));

        jButton3.setText("x");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 510, 720));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("welcome To");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 80, 110, 30));
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 50, 30));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_emailActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if(validateSignup()==true){
         if(checkDuplicateUser()==false){
             insertSignupDetails();
         }else{
              JOptionPane.showMessageDialog(this,"user already exit");}
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   library_loginpage home=new library_loginpage();
       home.setVisible(true);
      this. dispose();       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost
      if(checkDuplicateUser()==true){
           JOptionPane.showMessageDialog(this,"user already exit");}
    }//GEN-LAST:event_txt_usernameFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signuppage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new signuppage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField txt_contact;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_passward;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables

    private static class PreparedS {

        public PreparedS() {
        }
    }

    private static class PrepareStatement {

        public PrepareStatement() {
        }

        private void setString(int i, String name) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
